### PR TITLE
V2 launch

### PR DESCRIPTION
**Pull request by ukolka**
I believe this addresses every bullet point in the issue.

### CODE REVIEW

**Comment by ozan** [comment]
Thank you so much @ukolka ! Just wanted to let you know that I'm looking forward to reviewing this and your other PRs over the weekend :)

**Comment by ukolka** [comment]
@ozan no pressure. Would you be able to tell at a glance that what I've done so far is _seemingly_ correct? Just so I have more confidence making further contributions. I don't wan't to get too far in and discover there was something cardinally wrong with my approach.

**Comment by ozan** [comment]
@ukolka apologies again for the delay! Everything does look overall correct. The main feedback I'd have at this point is that some exercises on exercism are much more MIPS friendly than others... most of the ones you've chosen are in fact like that, but actually Hello World I would suggest is not :)

**Comment by ErikSchierboom** [comment]
This seems to have since been implemented.

**Pull request closed without merging**
