### PR TITLE
Add hello-world exercise

### PR DESCRIPTION
**Pull request by bergjohan**
@ErikSchierboom Could you verify this?

Ref: #90

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Works perfectly! Could you add an empty `impl.mips` file too? See https://github.com/exercism/mips/pull/91/files for more information.

**Comment by bergjohan** [comment]
Nice! Sure, I will add that later today. Should I add myself in "authors" in `.meta/config.json` or as contributor, or leave it empty?

**Comment by ErikSchierboom** [comment]
@bergjohan You should absolutely put yourself in the authors field!

**Comment by bergjohan** [comment]
Does this look okay?

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@bergjohan Yes, perfect! Feel free to merge!

**Comment by bergjohan** [comment]
Thanks, but I'm not able to merge, since I don't have write access to this repository. Are you able to merge, or do you know anyone who could help?

**Comment by ErikSchierboom** [comment]
No problem, I can merge. Thanks a ton!

**Pull request merged**
