### PR TITLE
maintainers: make ozan an alumnus

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@ozan Wanna make merging this your last maintainer action? :)

**Comment by ozan** [comment]
Sounds good, and thank you!

**Comment by ozan** [comment]
Wait, it looks like I no longer have write access :)

**Comment by ErikSchierboom** [comment]
Whoops! My bad. I've merged.

**Comment by kytrinyx** [comment]
@ozan ❤️ Thanks for making the MIPS track happen! It's been a good ride; good luck with all the other gazillion things you're working on :)

**Comment by ozan** [comment]
Thanks @kytrinyx ! Sorry I couldn't put more time into it :)

**Pull request merged**
